### ISSUE TITLE
Render Progress Feature

### ISSUE THREAD

**Issue by mikeycal** [mikeycal/the-video-editors-render-script-for-blender#1]
It would be nice if someone could figure out a way to add a render progress indicator to this script. 
Ideally, such a feature would need to work in cmd.exe as well as bash shell. It may require different code for each environment. In addition it would be nice if the feature could be turned on and off in the script, since such a feature may lead to render slowdown.

**Comment by aini-naire** [comment]
I had some ideas of how it could be done if the blender instances ran out of the python script (create a thread to watch the stdout of each instance and register a handler with blender in the overridesettings script to clear the stdout and print something unique when a frame is rendered).

Since on Windows it executes from a batch, that makes things a bit harder.
Since I know nothing about batch, I won't explore that possibility and I'll rule out geral progress.
Displaying progress by instance is possible using the overridesettings script but I can't figure out how to keep the output clean and clear it in a way it doesn't mess with the other progress bars, or something.

**Comment by mitxela** [comment]
Hi Mikeycal, thank you for making this excellent script.

I have added a very simple progress indicator that just captures the output and counts the rendered frames. I've only tested it on Linux and Windows, and with only a couple of .blend files, but it seems to work OK. There is probably some overhead added from this, I can't really tell but a flag to turn off the progress indicator could be added if it's a problem.

I'll submit a pull request, feel free to merge it, ignore it, or use it as inspiration for something else.

Cheers,
mitxela
