### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by Astra3** [mikeycal/the-video-editors-render-script-for-blender#10]
I don't truly think this is an issue, because script ran before just fine.
So, I prepared my video to render and save everything as it should be. After that I ran the script, that started perfectly and because my PC is not a very powerful machine I let it run for a while. After a half hour of rendering I checked how it goes and it drastically slowed down. It renders 1 frame per...0.2 seconds, but it rendered 1 frame per 48 seconds. And I noticed this began to happen after this:
Error, region type 4 missing in - name:"Action", id:12

Blender quit.

So I tried different container (changed from AVI to Matroska) and it still continued to happen but on different frame...I am using Ubuntu 16.04.2, Steam version of Blender 2.79. I rendered on the same computer in the same version of Blender by the same script a video and it ended up as expected...but this doesn't work as it should.

*Sorry for my English, I didn't born in English speaking country.

**Comment by mikeycal** [comment]
I have noticed that VSE rendering in Blender 2.79 is much glitchier than 2.78c. For this reason, I have reverted back to 2.78c for all my video editing needs. They overhauled the encoding section in blender 2.79 and they have apparently created some bugs due to that overhaul. I would report any bugs that you find in 2.79 and stick with 2.78c for all your video editing needs.

**Comment by Astra3** [comment]
Ok thank you, so I'm going to look if someone didn't report that bug and if not, I'm gonna report it.

**Comment by Astra3** [comment]
The problem has to be on script's side. It is also happening in 2.78c, but Blender renders it all just fine.

**Comment by mikeycal** [comment]
My guess is that you're running out of memory. Check memory usage when blender starts and compare it to memory usage when you start seeing the Slowdown. A workaround for memory issues would be to reduce the number of CPU Cores that the script is using because each core will start a unique blender instance. The more blender instances you are running, the more memory required.

In the script, set "reserved_cpu_logical_cores" to 1 or higher to force the script to open less instances of blender.

That setting represents the number of cpu cores not to use. So if you have a quad core CPU and you set it to 2, it will only create 2 blender instances.

**Comment by Astra3** [comment]
No, I found the problem. I am using Linux and the path to blender was set to "blender", like it should be.
But the Blender from repository is 2.76. So I set manually the right path to Blender and now it is fine.
