### ISSUE TITLE
Audio exporting problems

### ISSUE THREAD

**Issue by renatorroliveira** [mikeycal/the-video-editors-render-script-for-blender#5]
Hi there,
I was having some problems with the initial audio exporting.
When I was rendering a long video (250k frames) with source audio encoding in AAC @ 128kbps (GoPro video) it tooks about 25 minutes just to export the audio file. So far ok, but when I  tried to render a 313k frames video it stucked for hours and stopped with error status and no message.

I didn't understood why this audio file exporting is necessary. It is really necessary? Or can I adapt this process without it?

**Comment by mikeycal** [comment]
The one part of this script that doesn't use multiple CPU cores is the audio render. This is done because ffmpeg has issues combining audio files without noticable artifacts at the stitch locations. So to get high quality audio, we render the audio in one piece with one core. The good news is that audio renders are way faster than video renders when only using one core. So the script renders the audio for the whole project, then it starts the multicore render of the video. Finally it combines the audio and video together. 

Now, you mentioned that your video is 313,000 frames. If this is the case, the problem is that your total blender project goes over the blender project frame number limit. Blender can't render more than 300,000 frames. This is a hard limit that is built into blender.

**Comment by mikeycal** [comment]
By the way, if you don't need audio in your project, set the audio codec to none in your blender render properties and blender will skip the audio encode and go right to the multicore video encode.

**Comment by mikeycal** [comment]
I'm surprised that blender would even let you import more than 300,000 frames. It should block it. But I'm guessing blender may have been confused if you audio and video strips were different lengths.

**Comment by renatorroliveira** [comment]
Hmm, very strange in fact because I was able to import, cut and render inside blender (it tooked more than 4 hours, but blender did it!). I am using v2.78, maybe they removed this limitation? Or is due to my hardware? It is an i7-6800k @4.2GHz, 16GB @3200MHz and a GTX 1080 OC edition.

But my main concern is the audio export to the WAV file, that part is the one that stucked for me. I thought that this was done by ffmpeg, not by blender. If this is the case, did FFMPEG setted a hard limit on audio too?

**Comment by mikeycal** [comment]
Holy Crap! It appears that they lifted the limit in blender 2.78 to 500,000 Frames. This is odd. I am wondering if this is actually a glitch. The 300,000 frame limit has been around forever.

Audio is extracted from blender as a Lossless PCM WAV file using blender's audio export feature. Then that complete wav file is transcoded to something like AAC or MP3 using FFmpeg. This was required because FFmpeg had issues stitching audio together.
This might sound like a dumb question but did you install ffmpeg and configure the paths to point at it in the script? It sounds like blender may not be finding FFmpeg.

**Comment by renatorroliveira** [comment]
Yeah, I did it.
Before it stucked, I was able to render another project with fewer frames.
The error on the audio happened just one time =/

**Comment by mikeycal** [comment]
I did a test render of 500,000 frame yesterday, just to make sure that the script could render a video that long. It worked perfectly. So frame length  isn't the problem. 
What else can you tell me about this project that would help me reproduce the error?

**Comment by renatorroliveira** [comment]
@mikeycal I reloaded the video into a new project and did some additional adjustments.
I cutted out some frames and inserted some transitions and keyframes.
But one of these adjustments wasn't applied to the final rendered video.
I setted the audio strip to be Mono and setted the Pan level to 1.0, because the audio was full of noise and echo. But it din't stuck, I rendered everything in 1h 59m, 312k frames, 2h 47m of video.

But the Pan level not being applied... I believe is a bug right?
I will attach the .blend file, you won't be able to render it, but you can see the settings I am using.
I don't have the .blend file that crashed the audio extraction anymore...


[1.blend.zip](https://github.com/mikeycal/the-video-editors-render-script-for-blender/files/1015577/1.blend.zip)

**Comment by mikeycal** [comment]
As of Blender 2.78c, The audio "Pan" option seems to be completely broken in Blender. Pan will work with this script, but only if it also works with Blender. I just reported it as a bug so let's hope they fix it in the next release. 
https://developer.blender.org/T51574

UPDATE
I figured out the issue with PAN.
Your imported audio has a sample rate of 48kHz but your audio preferences have a setting of 44.1kHz.

Go to File -> User Preferences
Select the SYSTEM tab
In sound section, set Sample Rate to 48kHz and "Save user Settings"
Now the Pan should work on your audio after restarting blender.
You may also need to set Sample Rate for rendering by going the the SCENE tab and Putting in a Rate setting in the audio section of "48000" 

Also, remember that full Left ear sound is -1 and full right ear sound is +1
-2 and +2 is actually for rear speaker sound. But it will just sound like full sound on earphones.

**Comment by mikeycal** [comment]
@renatorroliveira are you still having issues with rendering?

**Comment by renatorroliveira** [comment]
With the render no.
I tested the Pan rendering inside Blender and it worked... at least the sound was very different than the original and the one rendered with the script.
But besides that the script is working well now, maybe it was the sound and file format used by the GoPro, I don't really know.
If this issue happens again I post here, but if you want you can close this one.

I will do some more tests with the Pan option.
