### ISSUE TITLE
I get a syntax error

### ISSUE THREAD

**Issue by SaccoSVD** [mikeycal/the-video-editors-render-script-for-blender#6]
Tried with Blender 2.78 (freshly installed) and latest FFmpeg.

When I run the command it gives me:

```
PS C:\Users\SACCO\Desktop> C:\Programas\Blender\Blender.exe -b vokko2.blend -P script.py
Read new prefs: C:\Users\SACCO\AppData\Roaming\Blender Foundation\Blender\2.78\config\userpref.blend
found bundled python: C:\Programas\Blender\2.78\python
read blend: C:\Users\SACCO\Desktop\vokko2.blend
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "C:\Users\SACCO\Desktop\script.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

Blender quit
PS C:\Users\SACCO\Desktop>

```
After that i thought I did something wrong with the script editor so I decided to try the default addresses to the letter as the tutorial explains and I still get the exact same error.

What can I do?

Thanks a lot in advance.

**Comment by mikeycal** [comment]
You downloaded the HTML version of the script. That is why it doesn't work.
Github requires that you go to the following Link:
https://github.com/mikeycal/the-video-editors-render-script-for-blender/blob/master/video_editors_render_script_v1.py

And RIGHT Click the "RAW" button.
Save Link As...

**Comment by SaccoSVD** [comment]
That did it :) thanks you!

OMG is using all 16 threads in my new Ryzen 1800x machine!

All my cores are pegged at 100% and the system is still responsive. I'm happily writing this now while rendering.

**Comment by SaccoSVD** [comment]
Rendering finishes. I see no video anywhere. Is the output taken from the blend project? mmmm is not where is supposed to be.

EDIT: Nah...I think I upsetted the script by clicking on the powershell trying to stop the text to see the times.

Second attempt is still rendering and took already longer. Shame there's no progress bar or something to know how far it is.

**Comment by SaccoSVD** [comment]
Audio Extract took 57 Seconds

 Audio Encode took 16 Seconds

 Render took 13 Minutes 47 Seconds

This was on a 20min video edition in Blender. It DRAMATICALLY lowered the render times.

This project was going to take more than 1h30m with blender alone. WOW!

Insanity..... thank you so much!

**Comment by mikeycal** [comment]
Make sure that you take your video project and SAVE AS... "1.blend" to the same directory as the render_script.py file.

This is necessary so that blender maintains the dynamic links to each of your source files in your project.

Also make sure that all the file paths to blender and ffmpeg are correct in the script. 

You can control how many cores of your CPU that you want to use by setting the the "reserved_cpu_logical_cores" setting on line 139 to more than 0.

1 will reserve 1 core for your background OS, 2 will reserve 2 cores... so on and so forth.

I wish I had a progress bar, but it is complicated due to the cross platform nature of this script.

**Comment by SaccoSVD** [comment]
I see:

```
#----[ NUMBER OF LOGICAL CPU CORES RESERVED TO RUN OPERATING SYSTEM ]          #  | I use a setting of 0 without any issues (I have a Intel i5 3570K w/ 16GB RAM)
reserved_cpu_logical_cores = 1 # (Default: 0) [1 = safe mode] 

```

I assume I can set the amount of cores I want to free up so windows doesn't choke. (in case it does), I plan to use "2" for that, as safe mode as described and also to try on helping further with temps.

Is there any way to tell Blender to use less CPU on each core? Like "blender, please, there are 14 threads available now....can we process things more relaxed?"

**Comment by mikeycal** [comment]
No, the operating system is actually responsible for how much of the core is used by each blender CORE instance. It will use less if it deems it necessary.

**Comment by SaccoSVD** [comment]
alright mate, awesome work on your script. I"m gonna be donating asap. This is a true time saver.

**Comment by SaccoSVD** [comment]
Donated already.

mmm, I've reserved 2 cores and the script is still using all cores/threads.

**Comment by SaccoSVD** [comment]
Reserved 4 cores. Still all pegged to 100%. Hmmm...

**Comment by mikeycal** [comment]
The way that it works is, a blender instance is created for each available core. You should see a blender process for each core if you use a process monitor. So if you have 16 logical cores, and you set reserved_cpu_logical_cores = 0, the script creates 16 blender instances as background processes. Each instance should only be able to use one core due to the fact that blender is hard coded to only use 1 core for an instance. 

Make sure that your setting has saved. If it is still doing it, I'm not sure why it would. Having said that, I've never tested on a Ryzen CPU. So I don't know if Ryzen reports Cores differently.

**Comment by SaccoSVD** [comment]
Yeah I guess is because is a Ryzen machine. I'm sure I've edited and saved the script correctly. Also set the wait time to 3s and it's reflected at the time to run the script. 

Anyway. I'm a happy lad now.

**Comment by mikeycal** [comment]
Please keep me upto date on any quirks you may notice using your Ryzen setup. One of the downsides to developing this script was that I only have a limited number of test environments.

**Comment by SaccoSVD** [comment]
I get 13 instances opened if I reserve 4 (so, close to 12)

it does seem to run more relaxed though. Good.
